# Generated by Django 3.1.3 on 2020-11-06 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('image', models.ImageField(null=True, upload_to='images/')),
                ('summary', models.CharField(max_length=200, null=True)),
                ('view', models.URLField(blank=True)),
                ('code', models.URLField(blank=True)),
            ],
        ),
    ]
